App\Entity\Category:
    exclusion_policy: all
    properties:
      id:
        expose: true
        groups: [category:collection, category:item, category:create, category:update, product:item, product:create, product:update]
      name:
        expose: true
        groups: [category:collection, category:item, category:create, category:update, product:item, product:create, product:update]
      description:
        expose: true
        groups: [category:collection, category:item, category:create, category:update, product:item,product:create, product:update]