<?php


namespace App\Controller\Api;


use App\Controller\BaseController;
use App\Entity\Category;
use App\Form\Category\CategoryFormType;
use App\Service\Category\CategoryServiceInterface;
use FOS\RestBundle\Controller\Annotations as Rest;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Rest\Route("/categories")
 * Class CategoryController
 * @package App\Controller\Api
 */
class CategoryController extends BaseController
{
	protected $formPost = CategoryFormType::class;
	protected $formUpdate = CategoryFormType::class;
	protected $entityClass = Category::class;
	protected $groupCollection = 'category:collection';
	protected $groupItem = 'category:item';
	protected $groupCreate = 'category:create';
	protected $groupUpdate = 'category:update';

	public function __construct(CategoryServiceInterface $service)
	{
		$this->service = $service;
	}

	/**
	 * @Rest\Get("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function collection(Request $request)
	{
		return parent::collection($request);
	}

	/**
	 * @Rest\Get("/{id}")
	 * @param Category $entity
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function itemElement(Category $entity)
	{
		return parent::item($entity); // TODO: Change the autogenerated stub
	}

	/**
	 * @Rest\Post("")
	 * @param Request $request
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function create(Request $request)
	{
		return parent::create($request);
	}

	/**
	 * @Rest\Patch("/{id}")
	 * @param Request $request
	 * @param Category $entity
	 * @param integer $id
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function patch(Request $request, Category $entity, int $id)
	{
		return parent::update($request, $entity);
	}

	/**
	 * @Rest\Put("/{id}")
	 * @param Request $request
	 * @param Category $entity
	 * @param integer $id
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function put(Request $request, Category $entity, int $id)
	{
		return parent::update($request, $entity, Request::METHOD_PUT);
	}

	/**
	 * @Rest\Delete("/{id}")
	 * @param Category $entity
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function remove(Category $entity)
	{
		return parent::delete($entity);
	}
}